### ISSUE TITLE
Cycle detected for Guid declaration

### ISSUE THREAD

**Issue by sir-pinecone** [ostef/Jai-Win32#1]
I ran `jai generate.jai - Devices.Display` and the generator eventually ends with `Cycle:
  [0] declaration of 'Guid' (Z:/dev/opensource/jai/Jai-Win32/.build/../Generated/Devices.Display.jai:1265)`. I seem to have the bindings I require (haven't checked for everything yet), so this likely isn't a blocker. 

I tried adding Guid to the blacklist but that didn't make a difference.

**Comment by ostef** [comment]
I checked it out and it's just the name of a member of the struct VIDEOPARAMETERS being the same as its type.
I implemented a basic hack to prevent this for function parameters so I just did the same for struct members (and function pointer types).

To fix this using the blacklist you would have had to add VIDEOPARAMETERS to the types to ignore, although this would probably cause other problems.

We might want to implement a better thing in the future but this specific issue is solved.
